version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: Mysqllocalhost123!
      MYSQL_DATABASE: oc_db
      MYSQL_USER: tester
      MYSQL_PASSWORD: Mysqllocalhost123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
