
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_ROOT_PASSWORD: Mysqllocalhost123!
      MYSQL_DATABASE: oc_db
      MYSQL_USER: tester
      MYSQL_PASSWORD: Mysqllocalhost123!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.server
    ports:
      - "8080:80"

volumes:
  mysql-data:
    name: "mysql-data"
